name: "Neolink"
description: "Will run Neolink directly as Add-on in HAOS"
version: "0.0.10"
slug: "neolink"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - i386
  - armv7
ports:
  8554/tcp: 8554
map:
  - type: addon_config
    read_only: False
  - type: homeassistant_config
    read_only: False
options:
  mode: rtsp
  log: info
schema:
  mode: list(rtsp|mqtt|dual|talk)
  log: list(info|warn|error|debug|trace)
